/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  phpSdkSidebar: [
    {
      type: 'autogenerated',
      dirName: 'php-sdk',
    },
  ],
  pythonSdkSidebar: [
    {
      type: 'autogenerated',
      dirName: 'python-sdk',
    },
  ],
  wordpressPluginSidebar: [
    {
      type: 'autogenerated',
      dirName: 'wordpress-plugin',
    },
  ],
};

export default sidebars;
